require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe KernelInfosController do

  def mock_kernel_info(stubs={})
    @mock_kernel_info ||= mock_model(KernelInfo, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all kernel_infos as @kernel_infos" do
      KernelInfo.stub(:all) { [mock_kernel_info] }
      get :index
      assigns(:kernel_infos).should eq([mock_kernel_info])
    end
  end

  describe "GET show" do
    it "assigns the requested kernel_info as @kernel_info" do
      KernelInfo.stub(:find).with("37") { mock_kernel_info }
      get :show, :id => "37"
      assigns(:kernel_info).should be(mock_kernel_info)
    end
  end

  describe "GET new" do
    it "assigns a new kernel_info as @kernel_info" do
      KernelInfo.stub(:new) { mock_kernel_info }
      get :new
      assigns(:kernel_info).should be(mock_kernel_info)
    end
  end

  describe "GET edit" do
    it "assigns the requested kernel_info as @kernel_info" do
      KernelInfo.stub(:find).with("37") { mock_kernel_info }
      get :edit, :id => "37"
      assigns(:kernel_info).should be(mock_kernel_info)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created kernel_info as @kernel_info" do
        KernelInfo.stub(:new).with({'these' => 'params'}) { mock_kernel_info(:save => true) }
        post :create, :kernel_info => {'these' => 'params'}
        assigns(:kernel_info).should be(mock_kernel_info)
      end

      it "redirects to the created kernel_info" do
        KernelInfo.stub(:new) { mock_kernel_info(:save => true) }
        post :create, :kernel_info => {}
        response.should redirect_to(kernel_info_url(mock_kernel_info))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved kernel_info as @kernel_info" do
        KernelInfo.stub(:new).with({'these' => 'params'}) { mock_kernel_info(:save => false) }
        post :create, :kernel_info => {'these' => 'params'}
        assigns(:kernel_info).should be(mock_kernel_info)
      end

      it "re-renders the 'new' template" do
        KernelInfo.stub(:new) { mock_kernel_info(:save => false) }
        post :create, :kernel_info => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested kernel_info" do
        KernelInfo.stub(:find).with("37") { mock_kernel_info }
        mock_kernel_info.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :kernel_info => {'these' => 'params'}
      end

      it "assigns the requested kernel_info as @kernel_info" do
        KernelInfo.stub(:find) { mock_kernel_info(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:kernel_info).should be(mock_kernel_info)
      end

      it "redirects to the kernel_info" do
        KernelInfo.stub(:find) { mock_kernel_info(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(kernel_info_url(mock_kernel_info))
      end
    end

    describe "with invalid params" do
      it "assigns the kernel_info as @kernel_info" do
        KernelInfo.stub(:find) { mock_kernel_info(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:kernel_info).should be(mock_kernel_info)
      end

      it "re-renders the 'edit' template" do
        KernelInfo.stub(:find) { mock_kernel_info(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested kernel_info" do
      KernelInfo.stub(:find).with("37") { mock_kernel_info }
      mock_kernel_info.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the kernel_infos list" do
      KernelInfo.stub(:find) { mock_kernel_info }
      delete :destroy, :id => "1"
      response.should redirect_to(kernel_infos_url)
    end
  end

end
