require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MachineActivationsController do

  # This should return the minimal set of attributes required to create a valid
  # MachineActivation. As you add validations to MachineActivation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all machine_activations as @machine_activations" do
      machine_activation = MachineActivation.create! valid_attributes
      get :index
      assigns(:machine_activations).should eq([machine_activation])
    end
  end

  describe "GET show" do
    it "assigns the requested machine_activation as @machine_activation" do
      machine_activation = MachineActivation.create! valid_attributes
      get :show, :id => machine_activation.id.to_s
      assigns(:machine_activation).should eq(machine_activation)
    end
  end

  describe "GET new" do
    it "assigns a new machine_activation as @machine_activation" do
      get :new
      assigns(:machine_activation).should be_a_new(MachineActivation)
    end
  end

  describe "GET edit" do
    it "assigns the requested machine_activation as @machine_activation" do
      machine_activation = MachineActivation.create! valid_attributes
      get :edit, :id => machine_activation.id.to_s
      assigns(:machine_activation).should eq(machine_activation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MachineActivation" do
        expect {
          post :create, :machine_activation => valid_attributes
        }.to change(MachineActivation, :count).by(1)
      end

      it "assigns a newly created machine_activation as @machine_activation" do
        post :create, :machine_activation => valid_attributes
        assigns(:machine_activation).should be_a(MachineActivation)
        assigns(:machine_activation).should be_persisted
      end

      it "redirects to the created machine_activation" do
        post :create, :machine_activation => valid_attributes
        response.should redirect_to(MachineActivation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved machine_activation as @machine_activation" do
        # Trigger the behavior that occurs when invalid params are submitted
        MachineActivation.any_instance.stub(:save).and_return(false)
        post :create, :machine_activation => {}
        assigns(:machine_activation).should be_a_new(MachineActivation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MachineActivation.any_instance.stub(:save).and_return(false)
        post :create, :machine_activation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested machine_activation" do
        machine_activation = MachineActivation.create! valid_attributes
        # Assuming there are no other machine_activations in the database, this
        # specifies that the MachineActivation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MachineActivation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => machine_activation.id, :machine_activation => {'these' => 'params'}
      end

      it "assigns the requested machine_activation as @machine_activation" do
        machine_activation = MachineActivation.create! valid_attributes
        put :update, :id => machine_activation.id, :machine_activation => valid_attributes
        assigns(:machine_activation).should eq(machine_activation)
      end

      it "redirects to the machine_activation" do
        machine_activation = MachineActivation.create! valid_attributes
        put :update, :id => machine_activation.id, :machine_activation => valid_attributes
        response.should redirect_to(machine_activation)
      end
    end

    describe "with invalid params" do
      it "assigns the machine_activation as @machine_activation" do
        machine_activation = MachineActivation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MachineActivation.any_instance.stub(:save).and_return(false)
        put :update, :id => machine_activation.id.to_s, :machine_activation => {}
        assigns(:machine_activation).should eq(machine_activation)
      end

      it "re-renders the 'edit' template" do
        machine_activation = MachineActivation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MachineActivation.any_instance.stub(:save).and_return(false)
        put :update, :id => machine_activation.id.to_s, :machine_activation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested machine_activation" do
      machine_activation = MachineActivation.create! valid_attributes
      expect {
        delete :destroy, :id => machine_activation.id.to_s
      }.to change(MachineActivation, :count).by(-1)
    end

    it "redirects to the machine_activations list" do
      machine_activation = MachineActivation.create! valid_attributes
      delete :destroy, :id => machine_activation.id.to_s
      response.should redirect_to(machine_activations_url)
    end
  end

end
