require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe NetAddressesController do

  def mock_net_address(stubs={})
    @mock_net_address ||= mock_model(NetAddress, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all net_addresses as @net_addresses" do
      NetAddress.stub(:all) { [mock_net_address] }
      get :index
      assigns(:net_addresses).should eq([mock_net_address])
    end
  end

  describe "GET show" do
    it "assigns the requested net_address as @net_address" do
      NetAddress.stub(:find).with("37") { mock_net_address }
      get :show, :id => "37"
      assigns(:net_address).should be(mock_net_address)
    end
  end

  describe "GET new" do
    it "assigns a new net_address as @net_address" do
      NetAddress.stub(:new) { mock_net_address }
      get :new
      assigns(:net_address).should be(mock_net_address)
    end
  end

  describe "GET edit" do
    it "assigns the requested net_address as @net_address" do
      NetAddress.stub(:find).with("37") { mock_net_address }
      get :edit, :id => "37"
      assigns(:net_address).should be(mock_net_address)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created net_address as @net_address" do
        NetAddress.stub(:new).with({'these' => 'params'}) { mock_net_address(:save => true) }
        post :create, :net_address => {'these' => 'params'}
        assigns(:net_address).should be(mock_net_address)
      end

      it "redirects to the created net_address" do
        NetAddress.stub(:new) { mock_net_address(:save => true) }
        post :create, :net_address => {}
        response.should redirect_to(net_address_url(mock_net_address))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved net_address as @net_address" do
        NetAddress.stub(:new).with({'these' => 'params'}) { mock_net_address(:save => false) }
        post :create, :net_address => {'these' => 'params'}
        assigns(:net_address).should be(mock_net_address)
      end

      it "re-renders the 'new' template" do
        NetAddress.stub(:new) { mock_net_address(:save => false) }
        post :create, :net_address => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested net_address" do
        NetAddress.stub(:find).with("37") { mock_net_address }
        mock_net_address.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :net_address => {'these' => 'params'}
      end

      it "assigns the requested net_address as @net_address" do
        NetAddress.stub(:find) { mock_net_address(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:net_address).should be(mock_net_address)
      end

      it "redirects to the net_address" do
        NetAddress.stub(:find) { mock_net_address(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(net_address_url(mock_net_address))
      end
    end

    describe "with invalid params" do
      it "assigns the net_address as @net_address" do
        NetAddress.stub(:find) { mock_net_address(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:net_address).should be(mock_net_address)
      end

      it "re-renders the 'edit' template" do
        NetAddress.stub(:find) { mock_net_address(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested net_address" do
      NetAddress.stub(:find).with("37") { mock_net_address }
      mock_net_address.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the net_addresses list" do
      NetAddress.stub(:find) { mock_net_address }
      delete :destroy, :id => "1"
      response.should redirect_to(net_addresses_url)
    end
  end

end
