require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShellSessionsController do

  # This should return the minimal set of attributes required to create a valid
  # ShellSession. As you add validations to ShellSession, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all shell_sessions as @shell_sessions" do
      shell_session = ShellSession.create! valid_attributes
      get :index
      assigns(:shell_sessions).should eq([shell_session])
    end
  end

  describe "GET show" do
    it "assigns the requested shell_session as @shell_session" do
      shell_session = ShellSession.create! valid_attributes
      get :show, :id => shell_session.id.to_s
      assigns(:shell_session).should eq(shell_session)
    end
  end

  describe "GET new" do
    it "assigns a new shell_session as @shell_session" do
      get :new
      assigns(:shell_session).should be_a_new(ShellSession)
    end
  end

  describe "GET edit" do
    it "assigns the requested shell_session as @shell_session" do
      shell_session = ShellSession.create! valid_attributes
      get :edit, :id => shell_session.id.to_s
      assigns(:shell_session).should eq(shell_session)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ShellSession" do
        expect {
          post :create, :shell_session => valid_attributes
        }.to change(ShellSession, :count).by(1)
      end

      it "assigns a newly created shell_session as @shell_session" do
        post :create, :shell_session => valid_attributes
        assigns(:shell_session).should be_a(ShellSession)
        assigns(:shell_session).should be_persisted
      end

      it "redirects to the created shell_session" do
        post :create, :shell_session => valid_attributes
        response.should redirect_to(ShellSession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shell_session as @shell_session" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShellSession.any_instance.stub(:save).and_return(false)
        post :create, :shell_session => {}
        assigns(:shell_session).should be_a_new(ShellSession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShellSession.any_instance.stub(:save).and_return(false)
        post :create, :shell_session => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shell_session" do
        shell_session = ShellSession.create! valid_attributes
        # Assuming there are no other shell_sessions in the database, this
        # specifies that the ShellSession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShellSession.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => shell_session.id, :shell_session => {'these' => 'params'}
      end

      it "assigns the requested shell_session as @shell_session" do
        shell_session = ShellSession.create! valid_attributes
        put :update, :id => shell_session.id, :shell_session => valid_attributes
        assigns(:shell_session).should eq(shell_session)
      end

      it "redirects to the shell_session" do
        shell_session = ShellSession.create! valid_attributes
        put :update, :id => shell_session.id, :shell_session => valid_attributes
        response.should redirect_to(shell_session)
      end
    end

    describe "with invalid params" do
      it "assigns the shell_session as @shell_session" do
        shell_session = ShellSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShellSession.any_instance.stub(:save).and_return(false)
        put :update, :id => shell_session.id.to_s, :shell_session => {}
        assigns(:shell_session).should eq(shell_session)
      end

      it "re-renders the 'edit' template" do
        shell_session = ShellSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShellSession.any_instance.stub(:save).and_return(false)
        put :update, :id => shell_session.id.to_s, :shell_session => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shell_session" do
      shell_session = ShellSession.create! valid_attributes
      expect {
        delete :destroy, :id => shell_session.id.to_s
      }.to change(ShellSession, :count).by(-1)
    end

    it "redirects to the shell_sessions list" do
      shell_session = ShellSession.create! valid_attributes
      delete :destroy, :id => shell_session.id.to_s
      response.should redirect_to(shell_sessions_url)
    end
  end

end
