require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SshCredentialsController do

  def mock_ssh_credential(stubs={})
    @mock_ssh_credential ||= mock_model(SshCredential, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all ssh_credentials as @ssh_credentials" do
      SshCredential.stub(:all) { [mock_ssh_credential] }
      get :index
      assigns(:ssh_credentials).should eq([mock_ssh_credential])
    end
  end

  describe "GET show" do
    it "assigns the requested ssh_credential as @ssh_credential" do
      SshCredential.stub(:find).with("37") { mock_ssh_credential }
      get :show, :id => "37"
      assigns(:ssh_credential).should be(mock_ssh_credential)
    end
  end

  describe "GET new" do
    it "assigns a new ssh_credential as @ssh_credential" do
      SshCredential.stub(:new) { mock_ssh_credential }
      get :new
      assigns(:ssh_credential).should be(mock_ssh_credential)
    end
  end

  describe "GET edit" do
    it "assigns the requested ssh_credential as @ssh_credential" do
      SshCredential.stub(:find).with("37") { mock_ssh_credential }
      get :edit, :id => "37"
      assigns(:ssh_credential).should be(mock_ssh_credential)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created ssh_credential as @ssh_credential" do
        SshCredential.stub(:new).with({'these' => 'params'}) { mock_ssh_credential(:save => true) }
        post :create, :ssh_credential => {'these' => 'params'}
        assigns(:ssh_credential).should be(mock_ssh_credential)
      end

      it "redirects to the created ssh_credential" do
        SshCredential.stub(:new) { mock_ssh_credential(:save => true) }
        post :create, :ssh_credential => {}
        response.should redirect_to(ssh_credential_url(mock_ssh_credential))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ssh_credential as @ssh_credential" do
        SshCredential.stub(:new).with({'these' => 'params'}) { mock_ssh_credential(:save => false) }
        post :create, :ssh_credential => {'these' => 'params'}
        assigns(:ssh_credential).should be(mock_ssh_credential)
      end

      it "re-renders the 'new' template" do
        SshCredential.stub(:new) { mock_ssh_credential(:save => false) }
        post :create, :ssh_credential => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ssh_credential" do
        SshCredential.stub(:find).with("37") { mock_ssh_credential }
        mock_ssh_credential.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :ssh_credential => {'these' => 'params'}
      end

      it "assigns the requested ssh_credential as @ssh_credential" do
        SshCredential.stub(:find) { mock_ssh_credential(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:ssh_credential).should be(mock_ssh_credential)
      end

      it "redirects to the ssh_credential" do
        SshCredential.stub(:find) { mock_ssh_credential(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(ssh_credential_url(mock_ssh_credential))
      end
    end

    describe "with invalid params" do
      it "assigns the ssh_credential as @ssh_credential" do
        SshCredential.stub(:find) { mock_ssh_credential(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:ssh_credential).should be(mock_ssh_credential)
      end

      it "re-renders the 'edit' template" do
        SshCredential.stub(:find) { mock_ssh_credential(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ssh_credential" do
      SshCredential.stub(:find).with("37") { mock_ssh_credential }
      mock_ssh_credential.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the ssh_credentials list" do
      SshCredential.stub(:find) { mock_ssh_credential }
      delete :destroy, :id => "1"
      response.should redirect_to(ssh_credentials_url)
    end
  end

end
